name: Sync Docs and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout main repo
        uses: actions/checkout@v4.1.0
          
      - name: Checkout gh repo
        uses: actions/checkout@v4.1.0
        with:
          repository: TD21forever/TD21forever.github.io
          ref: source
          path: gh
          token: ${{ secrets.TOKEN }}
          ssh-key: ${{ secrets.KEY }}

      - name: Copy docs from current repository to gh-source repository
        run: |
          cp -R docs/* gh/source/rssdocs/

      - name: Configure Git
        env:
          U_EMAIL: ${{ secrets.BOT_EMAIL }}
          U_NAME: ${{ secrets.BOT_NAME }}
        run: |
          git config --global user.name "${U_NAME}"
          git config --global user.email "${U_EMAIL}"
          cd gh

      - name: Check for changes
        run: |
          cd gh
          changes=$(git status --porcelain)
          if [[ -z $changes ]]; then
            echo "No changes to commit. Exiting..."
            exit 0
          else
            git add .
            git commit -m "Sync docs from main repository"
            git push origin source
          fi
